### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by 0xdad0** [ScreenNeuroPharmOrganization/screenneuropharmorganization.github.io#1]
- [x] rimuovere immagini con bordo e farle radius
- [x] aggiungere nuova pub
- [x] fix footer fixed quando lo schermo si riduce
- [x] sistemare contenuti home
- [ ] Modificare about me 
- [ ] Aggiungere logo spinoff
- [ ] Aggiungere Services (cioè quello che offrite) --> Athena e varie cose
- [ ] Ridimensionare immagine slidere home
